spring:
  rabbitmq:
    host: 10.43.2.242
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/moveon_boot?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-timeout: 30000
      idle-timeout: 60000
  redis:
    host: localhost
    port: 6379
gitee:
  clientId: 6ae933f941fabfb8cbc0496a14ee1807edbe7c24f444674be4d70ad9be767089
  clientSecret: a23831ce6fc7ea267ce032ec228f5a15b815a1d8e1a1700a8fa21dd1b0464ff4
  callBack: http://localhost:8080/sys/user/gitee
  state: GITEE
  user:
    prefix: ${gitee.state}@
    url: https://gitee.com/api/v5/user?access_token=
  token:
    url: https://gitee.com/oauth/token?grant_type=authorization_code&client_id=${gitee.clientId}&client_secret=${gitee.clientSecret}&redirect_uri=${gitee.callBack}&code=

netty:
  port: 8089

#moveon:
#  thread:
#    coreSize: 5
#    maxSize: 200
#    keepAliveSeconds: 30