spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moveon_boot?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-timeout: 30000
      idle-timeout: 60000
