moveon:
  machineId: 1

spring:
  application:
    name: moveon-boot
  profiles:
    active: dev
server:
  port: 8080

mybatis:
  type-aliases-package: com.moveon.**.entity
  mapper-locations: classpath*:mapper/**/*Mapper.xml
